# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shoppingapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for shoppingapp
  pod  'Firebase/Core'
  pod 'Firebase/Auth'
  target 'shoppingapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shoppingappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'shoppingapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for shoppingapp-tvOS

#  target 'shoppingapp-tvOSTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

#end
